# Generated by Django 3.1.4 on 2020-12-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201218_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sort_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
